### ISSUE TITLE
OSError: Cannot find empty port in range: 7860-7959

### ISSUE THREAD

**Issue by ngslabex** [cobanov/easy-web-summarizer#2]
Güzel çalışma için teşekkürler @cobanov 
Portainer'da çalıştırmayı denediğimde aşağıdaki hatayı alıyorum. 

`Traceback (most recent call last):
  File "/app/webui.py", line 52, in <module>
    demo.launch()
  File "/usr/local/lib/python3.9/site-packages/gradio/blocks.py", line 2205, in launch
    ) = http_server.start_server(
  File "/usr/local/lib/python3.9/site-packages/gradio/http_server.py", line 157, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 7860-7959. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.
`

Docker compose file:

```
version: "3.9"

services:
  ollama-container:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
  websum:
    image: web_summarizer
    ports:
      - "7860:7860"
    environment:
      - GRADIO_SERVER_NAME="0.0.0.0"
      - GRADIO_SERVER_PORT=7860
      - GRADIO_NUM_PORTS=100
    restart: unless-stopped
    networks:
      - host
networks:
  host:
    external: true
volumes:
  ollama: ~
```
